listen=YES
listen_ipv6=NO
background=NO

anonymous_enable=YES
no_anon_password=YES
anon_root=/srv/ftp
local_enable=NO
write_enable=NO
anon_upload_enable=NO
anon_mkdir_write_enable=NO

hide_ids=YES
seccomp_sandbox=NO

pasv_enable=YES
pasv_min_port=30000
pasv_max_port=30010

xferlog_enable=YES
xferlog_file=/var/log/vsftpd.log
